### ISSUE TITLE
Indicate if permissions have changed when using GET /user

### ISSUE THREAD

**Issue by IIIuminator** [BjoernPetersen/MusicBot-desktop#45]
Fail check or indicate otherwise (e.g. boolean in response body) if the permission in the JWT claims do not match the server permissions for that user

**Comment by BjoernPetersen** [comment]
As per the spec, `GET /user` should be a cheap operation to check whether the token is valid for the bot (matching signature) and decode it. That especially means that the bot won't to a database lookup every time the operation is called, so this suggestion is not really a practical.

**Comment by IIIuminator** [comment]
Right, makes sense. Not a big deal as a manual permission refresh is required anyway
