### ISSUE TITLE
Removing entry removes all instances of that entry

### ISSUE THREAD

**Issue by IIIuminator** [BjoernPetersen/MusicBot-desktop#47]
If the same person has queued the same title more than once and then wants to remove one of these instances all of them get removed. Probably more an API issue as the only information given are songId and providerId.
A quick fix could be to only remove the first/last occurrence of the song. Long term solution would be to add the position of the to be de-queued entry to the request body or generating a queueEntryId from songId, providerId, en-queuer and en-queue time

**Comment by BjoernPetersen** [comment]
The mere fact that the same entry can be added multiple times is a bug, actually. Normally, the queue shouldn't allow any duplicates. The root cause for the bug seems to be the same as for #46
