### ISSUE TITLE
Next song doesn't start by itself

### ISSUE THREAD

**Issue by IIIuminator** [BjoernPetersen/MusicBot-desktop#55]
When building from `develop` the playback stops after finishing the current song. It will continue when manually skipping the current song but otherwise just stop when it has ended. Behaviour is the same no matter if there is something in the queue or the auto-suggester is used.

**Comment by BjoernPetersen** [comment]
I assume you're testing with the Play Music plugin? It's working for me with Spotify. Could you try putting some YouTube songs in the queue and see if they auto-play?

**Comment by IIIuminator** [comment]
hmm. youtube playback doesn't seem to work at all. search and queuing works but playback just never happens. Trying to pause from a client results in an internal server error. Logs show an `IOException: Stream Closed at net.bjoernpetersen.musicbot.mpv.MpvPlayback$pause` (stackstrace cleaned of java internal calls)

**Comment by BjoernPetersen** [comment]
What version of the mpv plugin are you using?

**Comment by IIIuminator** [comment]
just tried with develop builds from both the youtube and mpv plugin. Was previously using the latest master builds (0.5.0 for mpv and 0.14.0 for yt) and the issue appears to be the same. I had one instance were it skipped the youtube songs and continued with gplay autosuggested ones but I can't reproduce it. That last occurrence does suggest that its an issue with the gplay plugin though

**Comment by BjoernPetersen** [comment]
You're testing on Linux, correct? If so, I guess it's a problem with the mpv plugin on Linux.

**Comment by IIIuminator** [comment]
Ah sorry yes, Manjaro Linux.

**Comment by BjoernPetersen** [comment]
Please try again with a clean Gradle rebuild (core library has been updated).

**Comment by IIIuminator** [comment]
after purging the gradle caches and build folders and rebuilding all plugins and the desktop client it now just skips enqd youtube videos. The next song does now properly start though so I'll be closing this issue. Any hint where to open one for the YT issue?

**Comment by BjoernPetersen** [comment]
Probably the mpv plugin, but I'm honestly not entirely sure. I can't recreate the issue right now (also on Manjaro Linux).

**Comment by IIIuminator** [comment]
hmm. I'll check my setup then (clearing configs etc.), maybe something is wrong, and create an issue if it still happens
